### ISSUE TITLE
Version 7.5 breaks something

### ISSUE THREAD

**Issue by Typhonling** [rushiranpise/xmlpak-RE#1]
Thanox doesn't work properly. And it seems to cause some other apps to crash, like some games.

**Comment by rushiranpise** [comment]
Hi, did 7.0 worked for you? 
which game specifically

**Comment by rushiranpise** [comment]
check with v 8.0

**Comment by Typhonling** [comment]
Both 7.0 and 8.0 also broke Thanox (xposed mode), while 6.5 didn't have this problem.
As for the game crashing, it's not necessarily caused by this module, I can't say for sure.
BTW, I'm going to deactivate this module and activate it only when needed in the future.

**Comment by rushiranpise** [comment]
What specifically it broke in thanox?

**Comment by Typhonling** [comment]
Thanox can't be activated correctly in lsposed with this module enabled, which means it's completely unavailable.

**Comment by rushiranpise** [comment]
Okay I will check

**Comment by rushiranpise** [comment]
![Screenshot_20231022-030110_Thanox](https://github.com/rushiranpise/xmlpak-RE/assets/37355997/80f5f42a-8796-4bb4-902f-bbf7270fe0ed)
![Screenshot_20231022-030331_Thanox](https://github.com/rushiranpise/xmlpak-RE/assets/37355997/939234df-9551-4bfd-9eef-41166cb67582)

**Comment by rushiranpise** [comment]
I have closed the issue since im able to use the app you mentioned with the latest version.

if you still have issue give a proper explanation with screen recording.

**Comment by Typhonling** [comment]
Thanks, maybe it's an isolated case or a conflict with something else.
This issue is low priority and doesn't need much attention.
